FROM nginx:1.17.4-alpine

RUN apk add --no-cache bash

# reactが立ち上がるまで待つためのモジュール
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait

RUN rm /etc/nginx/conf.d/default.conf
COPY default.dev.conf /etc/nginx/conf.d